version: "3"

services:
  emqx:
    restart: unless-stopped
    image: emqx:5.0.26
    container_name: emqx
    environment:
      - EMQX_AUTHORIZATION__SOURCES=[]
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
  web:
    build: ./client
    ports:
      - 80:80
  # mumble-server:
  #   image: mumblevoip/mumble-server:latest
  #   platform: linux/amd64
  #   container_name: mumble-server
  #   hostname: mumble-server
  #   restart: on-failure
  #   ports:
  #     - 64738:64738
  #     - 64738:64738/udp
  #   environment:
  #     MUMBLE_CONFIG_SERVER_PASSWORD: Hello
